# Use official Golang image as a builder
FROM golang:1.21 AS builder

# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o port-service ./cmd/main.go

# Use a minimal base image for the final container
FROM alpine:latest

# Set working directory
WORKDIR /root/

# Copy the built binary from builder stage
COPY --from=builder /app/port-service .

# Expose the application's port
EXPOSE 8080

# Run the service
CMD ["./port-service"]
